spring:
  datasource:
    url: jdbc:oracle:thin:@myprojectdb_medium?TNS_ADMIN=C:/Users/82106/arthomepage/lastartwebsite/Wallet_myprojectdb
    username: ADMIN
    password: riFUz5Fz+2N$eFY
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect